apiVersion: v1
kind: Pod
metadata:
  name: model-pod
spec:
  containers:
  - name: model-container
    image: dbswlgp99/edge-image:63
    securityContext:
      privileged: true
  restartPolicy: OnFailure

