apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      securityContext:
        privileged: true
      containers:
      - name: model-container
        image: dbswlgp99/edge-image:107

